
          export const LanguagesConstant: Record<string, number> = {
  "Arabic": 1,
  "Chinese (Simplified)": 2,
  "Chinese (Traditional)": 3,
  "Czech": 4,
  "Danish": 5,
  "Dutch": 6,
  "English": 7,
  "English (UK)": 8,
  "Spanish (Spain)": 9,
  "Spanish (Mexico)": 10,
  "Finnish": 11,
  "French": 12,
  "Hebrew": 13,
  "Hungarian": 14,
  "Italian": 15,
  "Japanese": 16,
  "Korean": 17,
  "Norwegian": 18,
  "Polish": 19,
  "Portuguese (Portugal)": 20,
  "Portuguese (Brazil)": 21,
  "Russian": 22,
  "Swedish": 23,
  "Turkish": 24,
  "Thai": 25,
  "Vietnamese": 26,
  "German": 27,
  "Ukrainian": 28
};
          export const InvertedLanguagesConstant: Record<number, string> = {
  "1": "Arabic",
  "2": "Chinese (Simplified)",
  "3": "Chinese (Traditional)",
  "4": "Czech",
  "5": "Danish",
  "6": "Dutch",
  "7": "English",
  "8": "English (UK)",
  "9": "Spanish (Spain)",
  "10": "Spanish (Mexico)",
  "11": "Finnish",
  "12": "French",
  "13": "Hebrew",
  "14": "Hungarian",
  "15": "Italian",
  "16": "Japanese",
  "17": "Korean",
  "18": "Norwegian",
  "19": "Polish",
  "20": "Portuguese (Portugal)",
  "21": "Portuguese (Brazil)",
  "22": "Russian",
  "23": "Swedish",
  "24": "Turkish",
  "25": "Thai",
  "26": "Vietnamese",
  "27": "German",
  "28": "Ukrainian"
};
        